pipeline {
    agent any

    stages {
        stage('github checkout') {
            steps {
                powershell label: '', script: '''cd docker-spring-boot
                   mvn clean install package'''
            }
        }
        stage('Build') {
            steps {
                sh label: '', script: '''cd docker_spring_boot
                mvn clean install package'''
            }
        }
        stage('Deploy') {
            steps {
                echo 'Deploying....'
            }
        }
    }
}
